/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ArchitecturalGlassRouteImport } from './routes/architectural-glass'
import { Route as CareersRouteImport } from './routes/careers'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as InnovationRouteImport } from './routes/innovation'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SpecialityGlassRouteImport } from './routes/speciality-glass'
import { Route as SuntuitiveGlassRouteImport } from './routes/suntuitive-glass'
import { Route as WhyCreezaRouteImport } from './routes/why-creeza'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ArchitecturalGlassRoute = ArchitecturalGlassRouteImport.update({
  id: '/architectural-glass',
  path: '/architectural-glass',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersRoute = CareersRouteImport.update({
  id: '/careers',
  path: '/careers',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const InnovationRoute = InnovationRouteImport.update({
  id: '/innovation',
  path: '/innovation',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SpecialityGlassRoute = SpecialityGlassRouteImport.update({
  id: '/speciality-glass',
  path: '/speciality-glass',
  getParentRoute: () => rootRouteImport,
} as any)
const SuntuitiveGlassRoute = SuntuitiveGlassRouteImport.update({
  id: '/suntuitive-glass',
  path: '/suntuitive-glass',
  getParentRoute: () => rootRouteImport,
} as any)
const WhyCreezaRoute = WhyCreezaRouteImport.update({
  id: '/why-creeza',
  path: '/why-creeza',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/architectural-glass': typeof ArchitecturalGlassRoute
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/innovation': typeof InnovationRoute
  '/projects': typeof ProjectsRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/speciality-glass': typeof SpecialityGlassRoute
  '/suntuitive-glass': typeof SuntuitiveGlassRoute
  '/why-creeza': typeof WhyCreezaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/architectural-glass': typeof ArchitecturalGlassRoute
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/innovation': typeof InnovationRoute
  '/projects': typeof ProjectsRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/speciality-glass': typeof SpecialityGlassRoute
  '/suntuitive-glass': typeof SuntuitiveGlassRoute
  '/why-creeza': typeof WhyCreezaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/architectural-glass': typeof ArchitecturalGlassRoute
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/innovation': typeof InnovationRoute
  '/projects': typeof ProjectsRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/speciality-glass': typeof SpecialityGlassRoute
  '/suntuitive-glass': typeof SuntuitiveGlassRoute
  '/why-creeza': typeof WhyCreezaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/architectural-glass'
    | '/careers'
    | '/contact'
    | '/innovation'
    | '/projects'
    | '/services'
    | '/sitemap.xml'
    | '/speciality-glass'
    | '/suntuitive-glass'
    | '/why-creeza'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/architectural-glass'
    | '/careers'
    | '/contact'
    | '/innovation'
    | '/projects'
    | '/services'
    | '/sitemap.xml'
    | '/speciality-glass'
    | '/suntuitive-glass'
    | '/why-creeza'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/architectural-glass'
    | '/careers'
    | '/contact'
    | '/innovation'
    | '/projects'
    | '/services'
    | '/sitemap.xml'
    | '/speciality-glass'
    | '/suntuitive-glass'
    | '/why-creeza'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ArchitecturalGlassRoute: typeof ArchitecturalGlassRoute
  CareersRoute: typeof CareersRoute
  ContactRoute: typeof ContactRoute
  InnovationRoute: typeof InnovationRoute
  ProjectsRoute: typeof ProjectsRoute
  ServicesRoute: typeof ServicesRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SpecialityGlassRoute: typeof SpecialityGlassRoute
  SuntuitiveGlassRoute: typeof SuntuitiveGlassRoute
  WhyCreezaRoute: typeof WhyCreezaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/architectural-glass': {
      id: '/architectural-glass'
      path: '/architectural-glass'
      fullPath: '/architectural-glass'
      preLoaderRoute: typeof ArchitecturalGlassRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers': {
      id: '/careers'
      path: '/careers'
      fullPath: '/careers'
      preLoaderRoute: typeof CareersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/innovation': {
      id: '/innovation'
      path: '/innovation'
      fullPath: '/innovation'
      preLoaderRoute: typeof InnovationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/speciality-glass': {
      id: '/speciality-glass'
      path: '/speciality-glass'
      fullPath: '/speciality-glass'
      preLoaderRoute: typeof SpecialityGlassRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/suntuitive-glass': {
      id: '/suntuitive-glass'
      path: '/suntuitive-glass'
      fullPath: '/suntuitive-glass'
      preLoaderRoute: typeof SuntuitiveGlassRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/why-creeza': {
      id: '/why-creeza'
      path: '/why-creeza'
      fullPath: '/why-creeza'
      preLoaderRoute: typeof WhyCreezaRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ArchitecturalGlassRoute: ArchitecturalGlassRoute,
  CareersRoute: CareersRoute,
  ContactRoute: ContactRoute,
  InnovationRoute: InnovationRoute,
  ProjectsRoute: ProjectsRoute,
  ServicesRoute: ServicesRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SpecialityGlassRoute: SpecialityGlassRoute,
  SuntuitiveGlassRoute: SuntuitiveGlassRoute,
  WhyCreezaRoute: WhyCreezaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
